# Generated by Django 4.0 on 2021-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='address', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='city', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, default='county', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='number', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='111', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='postcode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='street', max_length=80),
        ),
    ]
